def search_sequential() -> int: ...
def search_sequential_release_gil() -> int: ...
def search_parallel() -> int: ...
def search_parallel_release_gil() -> int: ...
def search_with_threads() -> int: ...
def search_with_threads_release_gil() -> int: ...
